name: "GPT-4 PR Review"
description: "Automatically review PRs using GPT-4"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  openai-api-key:
    description: "OpenAI API Key"
    required: true
runs:
  using: "node16"
  main: "run.js"
